services:
  nuxt:
    build: .
    container_name: nuxt-fy-crud-laravel-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: ["sleep", "infinity"] 